export const GET_ALL_EMPLOYEE_PENDING="GET_ALL_EMPLOYEE_PENDING";
export const GET_ALL_EMPLOYEE_SUCCESS="GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_ERROR="GET_ALL_EMPLOYEE_ERROR";

export const ADD_EMPLOYEE_PENDING="ADD_EMPLOYEE_PENDING";
export const ADD_EMPLOYEE_SUCCESS="ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR="ADD_EMPLOYEE_ERROR";

export const EDIT_EMPLOYEE_PENDING="EDIT_EMPLOYEE_PENDING";
export const EDIT_EMPLOYEE_SUCCESS="EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_ERROR="EDIT_EMPLOYEE_ERROR";


export const EDIT_EMPLOYEE_STATUS_ERROR="EDIT_EMPLOYEE_STATUS_ERROR";
export const EDIT_EMPLOYEE_STATUS_PENDING="EDIT_EMPLOYEE_STATUS_PENDING";
export const EDIT_EMPLOYEE_STATUS_SUCCESS="EDIT_EMPLOYEE_STATUS_SUCCESS";